name: build
on: [push, pull_request]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        mongodb-version: [4.4, 4.2, 4.0, 3.6, 3.4, 3.2]
        include:
          - os: ubuntu-20.04
            mongodb-version: 4.4
          - os: ubuntu-18.04
            mongodb-version: 4.4
          - os: ubuntu-18.04
            mongodb-version: 4.2
          - os: ubuntu-18.04
            mongodb-version: 4.0
          - os: ubuntu-18.04
            mongodb-version: 3.6
          - os: ubuntu-16.04
            mongodb-version: 4.4
          - os: ubuntu-16.04
            mongodb-version: 4.2
          - os: ubuntu-16.04
            mongodb-version: 4.0
          - os: ubuntu-16.04
            mongodb-version: 3.6
          - os: ubuntu-16.04
            mongodb-version: 3.4
          - os: ubuntu-16.04
            mongodb-version: 3.2
    steps:
    - uses: ankane/setup-mongodb@v1
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - run: |
        mongo --eval "db.version()"
